# Generated by Django 4.2.18 on 2025-02-14 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventtype_student_cached_total_points_and_more'),
    ]

    operations = [
    ]
